@startuml
!global $IWD_DARK_BLUE = "#094785"
!global $IWD_LIGHT_BLUE = "#5DA2D7"
!global $IWD_LIGHT_BLUE_50PER = "#5DA2D780"
!global $IWD_MEDIUM_GREY = "#5E5F60"
!global $IWD_DARK_GREY = "#44546A"
!global $IWD_MEDIUM_LIGHT_GREY = "#808080"
!global $IWD_LIGHT_GREY = "#C8C8C8"
!global $IWD_LIGHT_GREY_50PER = "#C8C8C880"
!global $IWD_SAND = "#CFC7A4"
!global $IWD_PLUM = "#44276F"
!global $IWD_FLAME = "#C93E27"
!global $IWD_LIME = "#9AC73C"
!global $IWD_AMBER = "#E9BD3B"
!global $IWD_TEAL = "#33A6B2"

' The 2022 revisions to the palette colours

!global $IWD2_GREEN_BASE = "#A4C454"
!global $IWD2_GREEN_1 = "#ECF1DA"
!global $IWD2_GREEN_2 = "#DAE6B6"
!global $IWD2_GREEN_3 = "#C7DB93"
!global $IWD2_GREEN_4 = "#7B943E"
!global $IWD2_GREEN_5 = "#526227"

!global $IWD2_TEAL_BASE = "#5C90C8"
!global $IWD2_TEAL_1 = "#DDE8F4"
!global $IWD2_TEAL_2 = "#BCD2E8"
!global $IWD2_TEAL_3 = "#9BBCDD"
!global $IWD2_TEAL_4 = "#3D6CA0"
!global $IWD2_TEAL_5 = "#28486B"

!global $IWD2_RED_BASE = "#CD5E45"
!global $IWD2_RED_1 = "#F3DED9"
!global $IWD2_RED_2 = "#E9BDB3"
!global $IWD2_RED_3 = "#DF9C8D"
!global $IWD2_RED_4 = "#A5402A"
!global $IWD2_RED_5 = "#6D2A1C"

!global $IWD2_RED_BASE = "#CD5E45"
!global $IWD2_RED_1 = "#F3DED9"
!global $IWD2_RED_2 = "#E9BDB3"
!global $IWD2_RED_3 = "#DF9C8D"
!global $IWD2_RED_4 = "#A5402A"
!global $IWD2_RED_5 = "#6D2A1C"

!global $IWD2_PLUM_BASE = "#A7559F"
!global $IWD2_PLUM_1 = "#ECDCEB"
!global $IWD2_PLUM_2 = "#D9B9D8"
!global $IWD2_PLUM_3 = "#C897C4"
!global $IWD2_PLUM_4 = "#7D3E77"
!global $IWD2_PLUM_5 = "#52294F"

!global $IWD2_GREY_BASE = "#E7E6E6"
!global $IWD2_GREY_1 = "#D0CECE"
!global $IWD2_GREY_2 = "#AEABAB"
!global $IWD2_GREY_3 = "#747070"
!global $IWD2_GREY_4 = "#393838"
!global $IWD2_GREY_5 = "#171616"

!global $IWD2_DARK_BLUE_BASE = "#1D5294"
!global $IWD2_DARK_BLUE_1 = "#BEDDFC"
!global $IWD2_DARK_BLUE_2 = "#80BBF9"
!global $IWD2_DARK_BLUE_3 = "#4A9BF7"
!global $IWD2_DARK_BLUE_4 = "#123967"
!global $IWD2_DARK_BLUE_5 = "#0B2849"

!global $IWD2_LIGHT_BLUE_BASE = "#2C72CC"
!global $IWD2_LIGHT_BLUE_1 = "#C8E2FB"
!global $IWD2_LIGHT_BLUE_2 = "#94C7FA"
!global $IWD2_LIGHT_BLUE_3 = "#63ABF8"
!global $IWD2_LIGHT_BLUE_4 = "#1F5599"
!global $IWD2_LIGHT_BLUE_5 = "#143D6E"

!global $IWD2_AMBER_BASE = "#FFB400"

' 2023 Brand revisions

!global $IWD3_GREEN = "#6BCB77"
!global $IWD3_GREEN_20 = "#E1F5E4"
!global $IWD3_GREEN_40 = "#C4EAC9"
!global $IWD3_GREEN_60 = "#A6E0AD"
!global $IWD3_GREEN_80 = "#89D592"

!global $IWD3_RED = "#FF6B6B"
!global $IWD3_RED_20 = "#FFE1E1"
!global $IWD3_RED_40 = "#FFC4C4"
!global $IWD3_RED_60 = "#FFA6A6"
!global $IWD3_RED_80 = "#FF8989"

!global $IWD3_SKY = "#009ADE"
!global $IWD3_SKY_20 = "#CCEBF8"
!global $IWD3_SKY_40 = "#99D7F2"
!global $IWD3_SKY_60 = "#66C2EB"
!global $IWD3_SKY_80 = "#33AEE5"

!global $IWD3_YELLOW_20 = "#FFF7D8"
!global $IWD3_YELLOW_40 = "#FFEFB1"
!global $IWD3_YELLOW_60 = "#FFE88B"
!global $IWD3_YELLOW_80 = "#FFE064"

!global $IWD3_CLOUD = "#F0F0F0"
!global $IWD3_STONE = "#CFD2E4"
!global $IWD3_MIDNIGHT = "#112D4E"


@enduml
