@startuml
!global $IWD_DARK_BLUE = "#094785"
!global $IWD_LIGHT_BLUE = "#5DA2D7"
!global $IWD_LIGHT_BLUE_50PER = "#5DA2D780"
!global $IWD_DARK_GREY = "#44546A"
!global $IWD_LIGHT_GREY = "#C8C8C8"
!global $IWD_LIGHT_GREY_50PER = "#C8C8C880"
!global $IWD_SAND = "#CFC7A4"
!global $IWD_PLUM = "#44276F"
!global $IWD_FLAME = "#C93E27"
@enduml
