sprite $azure [50x40/16z] {
rTC5hkGm40JG2fewNVS_xGIjyQn1Zd3_4uOQIWx_6ELB4lYE7_cEWoUTifi1b1mDE-aCE580OHSPSRMmmC8U0GTB4eVGjVDfUxuSjMFdqqfonScnJHTSX5JS
DZRDk2maFMw6BV4j-NxSJbX7N6QI6wAPTHQtS4SMUTR4iXCF4n0DoeergIb8M9P9BCc3Gsfh9WiN3-FNsamM6dDB1EPqI5lykydKI1QQDJtvQh8mUP5Bbl1I
YcLj91oAgUXSJtZAZbqMsCAKos_Vf9Am8ckHZVlx0vl6mNP0v0gj0tCcMxv9nITV63PjmPa1lwHUs4uecKil1siQXF-h7G
}
