sprite $azure [50x40/16z] {
rT97rkGW40DW5RZ9eFkVjdEevrSmzcx-RqiMmX_ZSL98E2VJGN12PG6Anr6kanx2XeEsGLOWa0671Dvve943HoJUDS3nBXrwyyC6H3uu_8CqFdG0dGyLQtxm
AG2UBnjMvBrWFB_mfMDApOe01jy2vXn_Hspy6BAEwHDfuLV6p8Ll0WWLXuckzWnK6cnHRrceNM0HlXNSkK5bm5Buvl7WgKNiw1drss3DIBXntufCfSoJRVfx
58-TOSGYVP5mejKxDwO92-tQ-Md2PHQy3YpfhUQvwy2SaIpjFhyLu-YqwAV-Ad4VsFCXgnKTAsvBfNCdm2JtZHjDGunRfDeM0lvNDm
}
