sprite $hyperledger [64x44/16z] {
vLQ7TeCm3CH13i93z_zVsw4kHm-ykjlBF7YdZUtbpyAvQUdA4Oh4DAxUHBNo_BEDnN4L83Efo15d0DU1f2EGRc9U8v1wGxXaYBSNlK0kVN8vTELIdm6N4O_l
H4X72X7fx5PIotNuYXCdQ6V0lZ9IRlaq44fGdUfOcRXHWklqGIxYZ9xB_pMg_mEYrHEW81LKw3EyqVDRj5oXL9R115aOEg7wRUAtUbBhXfRwv_evAlNMGvqw
KXkp_XKHyQH-m3ab5F3lw9-okVanFHYUtxSUp3u_pptuSAoL9OQl7UjNFZUDZlKhOpzVsBUE-04UMjWj20X7TWMfUoNCgxsu0N5W0qIugPJFmBxqWm6aRNso
vdS1yjYek1tb-I7vPHYq9wY9k5tUStxw1xW7
}
