sprite $aws [60x36/16z] {
vP9dOYWX28GVKhVE_M_xTaLCx_cNIH7B9mFhln-hYQ_x5ahtX4Ncib16D2A97NkUIz62abvJ0omtpXcj05ztRHZYOXaumiptN6HWoxG0zhmTEA__1x2PgEtG
wTXQ1Wwirm2Wcr9Kn81tGpw8QNgAycmCJmigiZukG7kxPtlVbL4cm6j6UzqfRxDvCsMP3I33bduYQpXUWPkQ2jDmjVGqSd6SqKYu0JYCdv2yOoZPF1kmEoFt
7b9zp8xJH1d0Pggs3fPwGyyRwmKVMCgV7vrknHw0PXH0ItD7B_Vky7f7ygWyEu6zqivmVWK5cc3FJPAqF4NxV5W2H3b8jcToUDhdm5fOoW2Px5PHBUw8etfh
LT9KpBmDkKa6b8KUqenQLgGvAd0ykWPRh4184OpQPqnR0CurrXELjk1Cxh3vEZEYSrgM0wcDdpqhpiy_bogYZ79Hp2sT_nqrLbMvsyFqDL9YoAvRGkahg0Wt
PeteBzQJ_feiR8nXxIi5qyr8JZWYNEXpeCIDHTHnikXu-n3qYE0B27-qwj5b_0PFoKKOzMu_ESOU9HDkZQWZHAsnsjnAnksv8uiFfArSqajZ_0vk_BZJhubO
_INtSHidtrZKt2_6BP_kR-i_
}
