sprite $aws_s3 [60x60/16z] {
xTG5pkn030DWPp13yVrF-vXQ_MaUY_OJxxOUi5ByDoylgTJMFsYjveIVbliyl3fJ2q9f67bchpc90119fNuEMnLFP9Ap2jvGz90ThcHKWIjFdWp7iU1QifcJ
tPWH42hUr2c8sCIRAWS2mxkkJAw41sMJrJlC8cVsIkYRDkc5KsMGDbkMQsXkuv2xeHEECm7KQIJjh3a-c7CTahJL4u1fSApzRHsTQn-pS_QQ-dqVUy4n305p
cxYVfjsdHzZWgDTRF2Jrrk8bpF-hCKElQOq2Xx3TJfyv1DyfuQ9UJj3I8gboBy8l-9j9igL1plJr_oEuyN9pJG14ltrlIAk_Md0_D4r8x9lg5-meYzoJ6OF5
BzWZRPEs5fjVy8DfO-qH5EpO2m-eyIJ41VkxYWkERoCks9-4k61d4gA2umF5HuelChvATZZ2WXCh7E6-2ZCUJIzSkXcUoURHad2HYcvo9aJg8iczvXYgEkRQ
9BcxuAVafdCVCzBixAKjuzUylBm7
}
