sprite $aws [60x36/16z] {
vL9POkmW35DMhxZtl-rBCBZxth-dTcOKWumiyl1hDEDZsqdZVd2pAbiaYy6CDkI-WJWneTUZ098BIx43yAlNZW6VMWTM4k4jYmxiUIo0BRi3o_Mz0hkOoWuj
nzAIC71SFm2wASLa3d0tn4DHfWkHUsbuEZ6PzDyJQEzdjlLL6sC2Va16_Q5wleFi73bc0qAmfn_A6LPxwv9KpMEuEhjrktG-6Bfc1x3AyxEziazjxYN8VQBt
3ACkyvR7enJ0Bgfo3ctqG9TRrWTUSKv_l7PrPRO2cen6aZlMFkwTy74pUpAUB7SU2IzQjw10Csov69QM2x5Lu0PGEKXj0up1QT_fEliP1B3IxiL6SGEjCrkP
8nMepct8nL1SuDaPY68j9zAxalVyf0rsEW2ogN3CTKVP0h0ST2mOnvOu3sT8bdOC5ajPjXM9FQM9fgAUrr-boI9P5arOj3tyLsYkgdR7u_4zfT60N5r8lwCs
Cs_kIjJVM4xrzo0auvUaVMVWk3MM3qv4RF4reT4j8wftHwZBswT29YA_1CHFgZpIy_QXZZ8SesVRd6c0nRn5H5gArbo51YIhB2yx2tq2RTFbwt32Fv2BFqtw
BOGhlzPz7cFfcviAywLXoLVth_4F
}
