sprite $aws_s3 [60x60/16z] {
xTG5qkmm30DW1Hm7hVkVzZ6ryxj-FBJVy6whWCRbV_FoSjOS_OCnvZxyQRjBnbKMNGoTbe0iVUvZHjBihFavh4u-CG5a6j-mD0EThfEWHjSMv4r7JYUuYfIS
x87DW47vfWvZ90dVDD4OQDvrRQ0UFbW5cDvXAY3RAw4N984N3hK691dRhg5xj0oKmGuwif2SaW2aNALz858p0AJQ3qb9TDJoRHsLMd9AEPSg-dqVfTBH4WEf
qN4_pRXFZs7GCQ-tc07ehSLBcF_NmAPUqmQC3iEudNwZ6RzJq0Mzd62S2a3jNeHVy3S2O9m6oFdwVpRUUBbx7fActxutG9g_Md3FI7fuq0lKBzYnAb04cmtB
BzXZem2fLWo_u0UIMYqjADXHAXz0uqc82_Pt5HSStqPSi3y9SS7E94G5nmUAZnHVP7oLw7I41HzCEi9zBMm-4Y_SUafyPWLPr-75MLe0EOpC2W2bIckgsgGM
02ZT-5FsK2av9I2bNAgEpL_pyl8U
}
