sprite $gcp [50x40/16z] {
nP9NakL020IfeXjq_mllZgydWTpO_5LaYAInFmCW0Ri8FFADwNOE8rTCs26OMHX70hCZi2jujYp9cyAIEmhtXKnqHef1c87pMNXhiSfebeEvv1jU1EGxxDkw
NypXpw2jg_4nNA1CMqleAsX29PqWz6tc6xCAlSAi2ho2PeiQh1Ta26nd8i2wOP_RnzqiYE-2GApU4TjM7XmT7mtO0KFjoh0Zg92B1cHSdCerbGmU6Q7oijt3
y4HvGM5guFeODTQ8HxA3Ebq9HuQELyAX4IOa71dh-unJ8oH8EJBS2ZxtZN3hWI05xBVv3m
}
